language: cpp

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode6.4

    - os: osx
      osx_image: xcode7.1
     
    - os: osx
      osx_image: xcode7.2

    - os: osx
      osx_image: xcode7.3

    - os: osx
      osx_image: xcode8

    - os: osx
      osx_image: xcode9.3

    - os: osx
      osx_image: xcode9.4

    - os: osx
      osx_image: xcode10

    - os: osx
      osx_image: xcode10.1

    - os: osx
      osx_image: xcode10.2

    - os: osx
      osx_image: xcode11.2

before_install:
  - brew update
  - brew tap nlohmann/json

script:
  - uname -a ; sw_vers ; $CXX --version
  - brew audit nlohmann_json
  - brew install nlohmann_json
  - brew test nlohmann_json
