language: cpp

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode9.3

    - os: osx
      osx_image: xcode9.4

    - os: osx
      osx_image: xcode10

    - os: osx
      osx_image: xcode10.1

    - os: osx
      osx_image: xcode10.2

    - os: osx
      osx_image: xcode10.3

    - os: osx
      osx_image: xcode11.2

    - os: osx
      osx_image: xcode11.3

    - os: osx
      osx_image: xcode11.4

    - os: osx
      osx_image: xcode11.5

    - os: osx
      osx_image: xcode11.6

before_install:
  - brew update
  - brew tap nlohmann/json

script:
  - uname -a ; sw_vers ; $CXX --version
  - brew audit nlohmann_json
  - brew install nlohmann_json
  - brew test nlohmann_json
